### ISSUE TITLE
issue while executing app.py

### ISSUE THREAD

**Issue by sama678** [adityagupta24/Covid19Detection#2]
i get this error AttributeError: 'Sequential' object has no attribute '_make_predict_function' please help

**Comment by adityagupta24** [comment]
Sorry @sama678 , I was a little late answering your query. So, this error comes because of changes to tensorflow. So, in current scenario tensorflow does not support _make_predict_function and moreover it is not needed anymore, so just comment out that line involving it. For your reference, I will just paste the file for you. Please revert back if any other issues occurs and at last I beg your pardon for answering the query a little late.
[model_synthesis.txt](https://github.com/adityagupta24/Covid19Detection/files/5163743/model_synthesis.txt)

**Comment by adityagupta24** [comment]
Also this previously commented code would work for tensorflow version less than 2 i.e. for v1.14 or v1.15.
For using tensorflow version greater than >v2.0 use the code that I am uploading in this comment. 
[model_synthesis.txt](https://github.com/adityagupta24/Covid19Detection/files/5164191/model_synthesis.txt)
